FROM python:3.13.6-alpine
ENV PYTHONUNBUFFERED=1
WORKDIR /app
COPY ./shifter/requirements.txt .
RUN pip install -r requirements.txt
COPY ./shifter/requirements_dev.txt .
RUN pip install -r requirements_dev.txt

COPY ./shifter/ .

RUN chmod +x ./entrypoint.sh

ENV APP_VERSION="DEV"
EXPOSE 8000
ENTRYPOINT ["/app/entrypoint.sh"]
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
