version: "3.9"

volumes:
  postgres_data:
  static:
  media:
   
services:
  db:
    image: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env
  web:
    build: .
    entrypoint: /home/app/web/entrypoint.sh
    command: gunicorn shifter.wsgi:application --bind 0.0.0.0:8000
    restart: always
    volumes:
      - static:/home/app/web/static
      - media:/home/app/web/media
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db
  nginx:
    build: ./nginx
    restart: always
    volumes:
      - static:/home/app/web/static
      - media:/home/app/web/media
    ports:
      - 1337:80
    depends_on:
      - web