FROM python:3.11-alpine
ENV PYTHONUNBUFFERED=1
WORKDIR /app
RUN apk add --update postgresql-dev gcc python3-dev musl-dev nodejs npm
COPY ./requirements.txt .
RUN pip install -r requirements.txt
COPY ./requirements_dev.txt .
RUN pip install -r requirements_dev.txt

COPY ./shifter/ .

RUN chmod +x ./entrypoint.sh
RUN chmod +x ./entrypoint_tailwind.sh

