version: "3.9"
name: shifter-dev
   
services:
  ## Uncomment this if you want to use postgres
  # db:
  #   image: postgres
  #   env_file:
  #     - ./.env.dev
  web:
    build:
      context: ../
      dockerfile: docker/Dockerfile.dev
    volumes:
      - ../shifter:/app
    env_file:
      - ../.env.dev
    ports:
      - "8000:8000"
