version: "3.9"
   
services:
  web:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    entrypoint: /home/app/web/entrypoint.sh
    command: python manage.py test
    restart: always
    env_file:
      - "../.env EXAMPLE"
    environment:
      - DJANGO_LOG_LEVEL=OFF
  nginx:
    build: ../nginx
    restart: always
    command: nginx -t
    depends_on:
      - web
    env_file:
      - "../.env EXAMPLE"