version: "3.9"

x-app: &default-app
  build:
    context: ../
    dockerfile: docker/Dockerfile.dev
  volumes:
    - ../shifter:/app
  env_file:
    - ../.env.dev
  
   
services:
  ## Uncomment this if you want to use postgres
  # db:
  #   image: postgres
  #   env_file:
  #     - ./.env.dev
  web:
    <<: *default-app
    entrypoint: /app/entrypoint.sh
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
  tailwind:
    <<: *default-app
    entrypoint: /app/entrypoint_tailwind.sh
    command: "python manage.py tailwind start"
    tty: true
