# Generated by Django 6.0 on 2026-01-02 22:45

import hashlib

from django.db import migrations, models


def calculate_file_hash(file_obj):
    """Calculate MD5 hash of file content in chunks."""
    hash_md5 = hashlib.md5()
    file_obj.seek(0)  # Reset file pointer to start
    for chunk in iter(lambda: file_obj.read(8192), b""):
        hash_md5.update(chunk)
    file_obj.seek(0)  # Reset for subsequent operations
    return hash_md5.hexdigest()


def backfill_file_hashes(apps, schema_editor):
    """Calculate and backfill MD5 hashes for existing files."""
    FileUpload = apps.get_model('shifter_files', 'FileUpload')

    # Get all files without a hash
    files_without_hash = FileUpload.objects.filter(file_hash__isnull=True)

    updated_count = 0
    error_count = 0

    for file_upload in files_without_hash:
        try:
            # Check if file exists
            if (file_upload.file_content and
                file_upload.file_content.storage.exists(
                    file_upload.file_content.name
                )):
                # Open and calculate hash
                with file_upload.file_content.open('rb') as f:
                    file_hash = calculate_file_hash(f)
                    file_upload.file_hash = file_hash
                    file_upload.save(update_fields=['file_hash'])
                    updated_count += 1
            else:
                # File doesn't exist on disk, skip
                error_count += 1
        except Exception as e:
            # Log error but continue processing other files
            print(
                f"Error calculating hash for "
                f"{file_upload.filename}: {e}"
            )
            error_count += 1

    if updated_count > 0 or error_count > 0:
        print(
            f"Backfilled {updated_count} file hashes. "
            f"Skipped {error_count} files."
        )


def reverse_backfill(apps, schema_editor):
    """Reverse migration - no action needed."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('shifter_files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='file_hash',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.RunPython(backfill_file_hashes, reverse_backfill),
    ]
