# Generated by Django 6.0 on 2026-01-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifter_files', '0002_fileupload_file_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='expiry_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
